spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gabozzago?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: pynn2409!

server:
  port: 8080